const PRODUCTS = [
 {
  "row": 1,
  "name": "Panetela sencilla",
  "cat": "cakes",
  "desc": "22cm de diámetro x 8cmde alto · Rellenos disponibles · Crema de leche · Chocolate · Fresa · Mantequilla Almendrado",
  "price": 5500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/panetela-sencilla-1.jpg"
 },
 {
  "row": 2,
  "name": "Cake media bandeja",
  "cat": "cakes",
  "desc": "Rellenos · Crema de leche · Fresa · Chocolate · Almendrado",
  "price": 6500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/cake-media-bandeja-2.jpg"
 },
 {
  "row": 3,
  "name": "Torta para 15 personalizada",
  "cat": "cakes",
  "desc": "4 capas de relleno · 2 pisos (22cmx 8 y 15cm×10)",
  "price": 12000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/torta-para-15-personalizada-3.jpg"
 },
 {
  "row": 4,
  "name": "Torta para 15 años",
  "cat": "cakes",
  "desc": "1 panetela 15cm×10cm · 2 panetelas 22cm x 8cm",
  "price": 15000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/torta-para-15-anos-4.jpg"
 },
 {
  "row": 5,
  "name": "Tortas temáticas",
  "cat": "cakes",
  "desc": "22cm×8cm · Rellenos opcionales · Leche condensada hervida o fanguito 500$ · Nuthela-800$ · Trozos de chocolate o Peter-500$",
  "price": 6000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/tortas-tematicas-5-0.jpg"
 },
 {
  "row": 6,
  "name": "Torta o pastel de 15 o para bodas",
  "cat": "cakes",
  "desc": "Diseños de 3 niveles 32cm de altura",
  "price": 22000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/torta-o-pastel-de-15-o-para-bodas-6.jpg"
 },
 {
  "row": 7,
  "name": "Torta chocolate especial",
  "cat": "cakes",
  "desc": "Rellenos · Nutella · Fanguito · Trozos de chocolate · 22cmx8cm",
  "price": 7000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/torta-chocolate-especial-7.jpg"
 },
 {
  "row": 8,
  "name": "Torta personalizada de 2 pisos",
  "cat": "cakes",
  "desc": "Doble relleno · 1(22cmx8) · 2(15cmx8)",
  "price": 9500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/torta-personalizada-de-2-pisos-8.jpg"
 },
 {
  "row": 9,
  "name": "Bandeja de 24 marquesitas",
  "cat": "cakes",
  "desc": "Bandeja de 24 marquesitas",
  "price": 4500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/bandeja-de-24-marquesitas-9.jpg"
 },
 {
  "row": 10,
  "name": "Cake Personalizado",
  "cat": "cakes",
  "desc": "8 panetelas de 15cm×10 de alto",
  "price": 25000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/cake-personalizado-10.jpg"
 },
 {
  "row": 11,
  "name": "Cake bandeja con piso superior",
  "cat": "cakes",
  "desc": "Personalizado a gusto",
  "price": 18000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/cake-bandeja-con-piso-superior-11.jpg"
 },
 {
  "row": 12,
  "name": "Cake premium",
  "cat": "cakes",
  "desc": "22cmx8cm · 3 capas y doble relleno · Personalizada.",
  "price": 7500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/cake-premium-12.jpg"
 },
 {
  "row": 13,
  "name": "Cake blanco y dorado con flores",
  "cat": "cakes",
  "desc": "Cake de dos niveles, decorado con delicadas flores en tonos blanco y amarillo y finos detalles dorados. Elaborado con ingredientes de alta calidad y diseñado para sorprender tanto por su belleza como por su delicioso sabor.",
  "price": 12000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/cake-13.jpg"
 },
 {
  "row": 14,
  "name": "Cake rectangular de 2 pisos",
  "cat": "cakes",
  "desc": "Totalmente personalizado",
  "price": 19500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/cake-rectangular-de-2-pisos-14.jpg"
 },
 {
  "row": 15,
  "name": "Torta tres leche",
  "cat": "cakes",
  "desc": "Relleno fanguito y trozos de chocolate · Cobertura de chocolate opcional",
  "price": 6500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/torta-tres-leche-15.jpg"
 },
 {
  "row": 16,
  "name": "Cake modelo rectangular doble",
  "cat": "cakes",
  "desc": "Con piso superior · Para 80 a 100 personas",
  "price": 30000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/cake-modelo-rectangular-doble-16.jpg"
 },
 {
  "row": 17,
  "name": "Torta tres pisos",
  "cat": "cakes",
  "desc": "Decoración para niña · 2 panetela22cmx8cm · 1 panetela 15cmx8cm",
  "price": 15000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/torta-tres-pisos-17.jpg"
 },
 {
  "row": 18,
  "name": "Cake temático Totalmente personalizado",
  "cat": "cakes",
  "desc": "Totalmente personalizado · 8 panetelas 22cmx8cm · 2 panetelas 15cmx8cm",
  "price": 48000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/cake-tematico-totalmente-personalizado-18.jpg"
 },
 {
  "row": 19,
  "name": "Cake para fiesta infantil",
  "cat": "cakes",
  "desc": "Modelo :8 panetelas 22cmx8cm",
  "price": 40000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎂",
  "img": "assets/products/cake-para-fiesta-infantil-19.jpg"
 },
 {
  "row": 20,
  "name": "Ancheta desayuno sorpresa",
  "cat": "hombre",
  "desc": "Presentación: · - Panetela · - Malta · - Cangrejito · - Hamburguesa · - Confitura · Color disponible · - verde · - azul · - rojo · - negro",
  "price": 12000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎩",
  "img": "assets/products/ancheta-desayuno-sorpresa-20.jpg"
 },
 {
  "row": 21,
  "name": "Ancheta de hombre",
  "cat": "hombre",
  "desc": "Presentación: · - Panetela · - Confitura · -Color disponible · - azul · - negro · - rojo · - verde",
  "price": 12000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎩",
  "img": "assets/products/ancheta-de-hombre-21.jpg"
 },
 {
  "row": 22,
  "name": "Ancheta de hombre",
  "cat": "hombre",
  "desc": "Presentación · - Confitura · Color disponible: · - negro · - azul · - verde · - rojo",
  "price": 7000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎩",
  "img": "assets/products/ancheta-de-hombre-22.jpg"
 },
 {
  "row": 23,
  "name": "Cesta de hombre",
  "cat": "hombre",
  "desc": "Presentación · - Botella de Ron · - confitura · Color disponible · - verde · - azul · - rojo",
  "price": 12000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎩",
  "img": "assets/products/cesta-de-hombre-23.jpg"
 },
 {
  "row": 24,
  "name": "Ancheta de hombre",
  "cat": "hombre",
  "desc": "Presentación: · - Sidra · - Nutella · - Confitura · Colores disponibles: · - negro · - verde · - azul · - dorado · - rojo",
  "price": 12000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎩",
  "img": "assets/products/ancheta-de-hombre-24.jpg"
 },
 {
  "row": 25,
  "name": "Ancheta mujer",
  "cat": "mujer",
  "desc": "Presentación · - Planeta · - Confitura · Color disponible · - rojo · - rosado · - morado · - amarillo · - naranja",
  "price": 12000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "💐",
  "img": "assets/products/ancheta-mujer-25.jpg"
 },
 {
  "row": 26,
  "name": "Ancheta de mujer",
  "cat": "mujer",
  "desc": "Presentación · - Panetela · - Peluche · - confitura · Color disponible · - rosado · - morado · - rojo · - amarillo · - naranja",
  "price": 17000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "💐",
  "img": "assets/products/ancheta-de-mujer-26.jpg"
 },
 {
  "row": 27,
  "name": "Ancheta mujer",
  "cat": "mujer",
  "desc": "Presentación · - panetela · - confitura · - taza personalizada · Color disponible · - rosado · - morado · - rojo · - amarillo · - naranja",
  "price": 14000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "💐",
  "img": "assets/products/ancheta-mujer-27.jpg"
 },
 {
  "row": 28,
  "name": "Ancheta de mujer",
  "cat": "mujer",
  "desc": "Presentación: · - Panetela · - Taza personalizada · - peluche · - confituras · Color disponible · - rosado · - morado · - rojo · - amarillo · - naranja",
  "price": 19000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "💐",
  "img": "assets/products/ancheta-de-mujer-28.jpg"
 },
 {
  "row": 29,
  "name": "Ancheta temática de niño",
  "cat": "nino",
  "desc": "Presentación · - mini panetela · - confituras · Color disponible · - azul · - rojo · - verde",
  "price": 10000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🧸",
  "img": "assets/products/ancheta-tematica-de-nino-29.jpg"
 },
 {
  "row": 30,
  "name": "Ancheta mujer con perfume",
  "cat": "mujer",
  "desc": "Presentación · - panetela · - perfume · - Confitura · Color disponible · - rosado · - morado · - rojo · - amarillo · - naranja",
  "price": 18000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "💐",
  "img": "assets/products/producto-30.jpg"
 },
 {
  "row": 31,
  "name": "Ancheta mujer",
  "cat": "mujer",
  "desc": "Presentación · - flores · - colonia · - taza personalizada · - confitura · Color disponible · - rosado · - morado · - rojo · - amarillo · - naranja",
  "price": 11000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "💐",
  "img": "assets/products/ancheta-mujer-31.jpg"
 },
 {
  "row": 32,
  "name": "Ancheta mujer",
  "cat": "mujer",
  "desc": "Presentación · - Sidra · - Panetela · - Nutella · - refresco · - confitura · Colores disponibles · - Rojo · - rosado · - morado · - amarillo · - naranja",
  "price": 16000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "💐",
  "img": "assets/products/ancheta-mujer-32.jpg"
 },
 {
  "row": 33,
  "name": "Ancheta con peluche y flores",
  "cat": "mujer",
  "desc": "Presentación · - peluche · - Flores · - Confitura",
  "price": 12500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "💐",
  "img": "assets/products/ancheta-33.jpg"
 },
 {
  "row": 34,
  "name": "Cesta con confitura",
  "cat": "mujer",
  "desc": "Cesta · Presentación · - confitura · Colores disponibles · - rosado · - morado · - rojo · - amarillo · - naranja",
  "price": 6000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "💐",
  "img": "assets/products/cesta-presentacion-34.jpg"
 },
 {
  "row": 35,
  "name": "Ancheta temática de niña",
  "cat": "nina",
  "desc": "Presentación · - panetela · - peluche · - Confitura · Colores disponibles · - rosado · - morado · - rojo · - amarillo · - naranja",
  "price": 17000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎀",
  "img": "assets/products/ancheta-tematica-de-nina-35.jpg"
 },
 {
  "row": 36,
  "name": "Cesta grande de niña",
  "cat": "nina",
  "desc": "Presentación · - confitura · - peluche · Colores disponibles · - rojo · - rosado · - amarillo · - morado · - naranja",
  "price": 12000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎀",
  "img": "assets/products/cesta-grande-de-nina-36.jpg"
 },
 {
  "row": 37,
  "name": "Ancheta de niña",
  "cat": "nina",
  "desc": "Presentación · - panetela · - Confitura · Color disponible · - rosado · - morado · - amarillo · - rojo · - naranja",
  "price": 12000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎀",
  "img": "assets/products/ancheta-de-nina-37.jpg"
 },
 {
  "row": 38,
  "name": "Ancheta globo burbuja de niña",
  "cat": "nina",
  "desc": "Presentación · - peluche · - confitura · - globo burbuja · Color disponible · - rojo · - rosado · - morado · - amarillo · - naranja",
  "price": 11000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎀",
  "img": "assets/products/ancheta-globo-burbuja-de-nina-38.jpg"
 },
 {
  "row": 39,
  "name": "Ancheta de niña",
  "cat": "nina",
  "desc": "Presentación · - flores · - peluche · - Nutella · - Confitura · Color disponible · - rojo · - rosado · - morado · - naranja · - amarillo · - negro y blanco",
  "price": 12000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎀",
  "img": "assets/products/ancheta-de-nina-39.jpg"
 },
 {
  "row": 40,
  "name": "Helado",
  "cat": "postres",
  "desc": "Disfruta de la textura más suave y cremosa con nuestro helado de vainilla tradicional.",
  "price": 3000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🥮",
  "img": "assets/products/helado-40.jpg"
 },
 {
  "row": 41,
  "name": "Pastelito",
  "cat": "postres",
  "desc": "Pastelito crujientes y elaboradas con ingredientes de alta calidad. Nuestros pastelitos artesanales en forma de flor están exquisito dulce que aporta el equilibrio perfecto entre textura y sabor. ideal para compartir en reuniones, celebraciones o regalar a alguien especial.",
  "price": 60,
  "unit": "unidad",
  "unit_label": "unidad",
  "icon": "🥮",
  "img": "assets/products/pastelito-41.jpg"
 },
 {
  "row": 42,
  "name": "Panes",
  "cat": "postres",
  "desc": "Panes artesanales suaves y frescos, con un ligero toque de ajonjolí. El complemento perfecto para nuestros combos de bufet, ideales para cualquier celebración o evento especial.",
  "price": 70,
  "unit": "unidad",
  "unit_label": "unidad",
  "icon": "🥮",
  "img": "assets/products/panes-42.jpg"
 },
 {
  "row": 43,
  "name": "Donas de Chocolate",
  "cat": "postres",
  "desc": "Esponjosas donas elaboradas con masa suave y fresca, cubiertas con una deliciosa capa de chocolate y decoradas con coloridas grageas. El postre perfecto para endulzar cualquier celebración, mesa de postres, bufet o compartir en familia.",
  "price": 60,
  "unit": "unidad",
  "unit_label": "unidad",
  "icon": "🥮",
  "img": "assets/products/donas-de-chocolate-43.jpg"
 },
 {
  "row": 44,
  "name": "Rosquillas",
  "cat": "postres",
  "desc": "Rosquillas deliciosas donas caseras, elaboradas con ingredientes frescos y una receta tradicional que les brinda una textura suave por dentro y un dorado perfecto por fuera",
  "price": 60,
  "unit": "unidad",
  "unit_label": "unidad",
  "icon": "🥮",
  "img": "assets/products/rosquillas-44.jpg"
 },
 {
  "row": 45,
  "name": "Empanaditas",
  "cat": "postres",
  "desc": "Deliciosas empanaditas de masa crujiente y dorada, rellenas con ingredientes seleccionados y preparadas al momento. Ideales como aperitivo, para bufets, fiestas y eventos, ofreciendo un sabor casero que encanta a todos.",
  "price": 60,
  "unit": "unidad",
  "unit_label": "unidad",
  "icon": "🥮",
  "img": "assets/products/empanaditas-45.jpg"
 },
 {
  "row": 46,
  "name": "Croqueta",
  "cat": "postres",
  "desc": "Deliciosas croquetas, elaboradas con una receta casera, doradas hasta alcanzar el punto perfecto y con un relleno suave y lleno de sabor.",
  "price": 45,
  "unit": "unidad",
  "unit_label": "unidad",
  "icon": "🥮",
  "img": "assets/products/croqueta-46.jpg"
 },
 {
  "row": 47,
  "name": "Churros",
  "cat": "postres",
  "desc": "Disfruta de nuestros deliciosos churros, preparados con una receta tradicional, dorados a la perfección y cubiertos con una fina capa de azúcar.",
  "price": 60,
  "unit": "unidad",
  "unit_label": "unidad",
  "icon": "🥮",
  "img": "assets/products/churros-47.jpg"
 },
 {
  "row": 48,
  "name": "Bolitas de queso",
  "cat": "postres",
  "desc": "Bolitas de queso, elaboradas con una receta casera y fritas hasta lograr un dorado perfecto. Crujientes por fuera, suaves por dentro y con un delicioso sabor a queso que conquista en cada bocado.",
  "price": 80,
  "unit": "unidad",
  "unit_label": "unidad",
  "icon": "🥮",
  "img": "assets/products/bolitas-de-queso-48.jpg"
 },
 {
  "row": 49,
  "name": "Ensalada fría",
  "cat": "postres",
  "desc": "Ensalada fría 8 Libras Disfruta de nuestra deliciosa ensalada fría, preparada con pasta, jamón, queso, aceitunas y un suave aderezo cremoso que combina perfectamente cada ingrediente.",
  "price": 6000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🥮",
  "img": "assets/products/ensalada-fria-49.jpg"
 },
 {
  "row": 50,
  "name": "Pasta",
  "cat": "postres",
  "desc": "1lib",
  "price": 900,
  "unit": "unidad",
  "unit_label": "libra",
  "icon": "🥮",
  "img": "assets/products/pasta-50.jpg"
 },
 {
  "row": 51,
  "name": "Ramo de 7 rosas eternas",
  "cat": "ramos",
  "desc": "Ramo pequeño · 7 rosas eternas pequeñas · Hojas artificiales · Decoración con media perla · Forrado decorativo · 1 mariposa · Florecitas boca de ángel (blancas)",
  "price": 6500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🌹",
  "img": "assets/products/ramos-51.jpg"
 },
 {
  "row": 52,
  "name": "Ramo de novia o 15 añera",
  "cat": "ramos",
  "desc": "15 rosas eternas · Decoración con media perla · Mariposa · Florecitas boca de ángel (blancas)",
  "price": 14500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🌹",
  "img": "assets/products/ramo-de-novia-52.jpg"
 },
 {
  "row": 53,
  "name": "Ramo de 10 rosas eternas",
  "cat": "ramos",
  "desc": "10 rosas eternas · Hojas artificiales · Decoración con media perla · Forrado decorativo · Mariposa · Florecitas boca de ángel (blancas) · Malla con bordes",
  "price": 10500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🌹",
  "img": "assets/products/ramo-53.jpg"
 },
 {
  "row": 54,
  "name": "Ramo de 5 rosas eternas",
  "cat": "ramos",
  "desc": "5 rosas eternas · Hojas artificiales · Decoración con media perla · Forrado decorativo · Mariposa · Florecitas boca de ángel (blancas)",
  "price": 7000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🌹",
  "img": "assets/products/ramo-54.jpg"
 },
 {
  "row": 55,
  "name": "Ramo de girasoles",
  "cat": "ramos",
  "desc": "15 girasoles eternos para 15 añera · Frase decorativa \"happy birthday\" · Color disponible · - amarillo · Forrado decorativo · Mariposa",
  "price": 10500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🌹",
  "img": "assets/products/ramo-de-girasoles-55.jpg"
 },
 {
  "row": 56,
  "name": "Ramo de 8 rosas eternas y peluche",
  "cat": "ramos",
  "desc": "8 rosas eternas · 1 peluche · Hojas artificiales · Forrado decorativo · Mariposa · Florecitas boca de ángel (blancas)",
  "price": 12500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🌹",
  "img": "assets/products/ramo-de-rosas-eternas-56.jpg"
 },
 {
  "row": 58,
  "name": "Ramo buchón",
  "cat": "ramos",
  "desc": "Presentación · - 7 rosas eternas · - una mariposa · - Florecitas boca de ángel (blancas) · Forrado decorativo",
  "price": 18500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🌹",
  "img": "assets/products/ramo-buchon-58.jpg"
 },
 {
  "row": 59,
  "name": "Ramo de 15 añera",
  "cat": "ramos",
  "desc": "15 rosas eternas · 1 corona decorativa · Hojas artificiales · Forrado decorativo · 1 mariposa · Florecitas boca de ángel (blancas)",
  "price": 10500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🌹",
  "img": "assets/products/ramo-de-15-anera-59.jpg"
 },
 {
  "row": 60,
  "name": "Sorpresa con disfraz",
  "cat": "sorpresas",
  "desc": "Puede agregar a sus regalos un momento mágico con nuestras entregas sorpresas, con disfraces y animaciones. · Canciones, dedicatorias, fotos y videos para inmortalizar el momento",
  "price": 8000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎭",
  "img": "assets/products/sorpresa-con-disfraz-60.jpg"
 },
 {
  "row": 61,
  "name": "Mariachi",
  "cat": "sorpresas",
  "desc": "Si lo que desea es dar un toque único a su sorpresa de cumpleaños nuestros mariachis harán su mejor show · Un repertorio de canciones para alegrar su celebración.",
  "price": 25000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎭",
  "img": "assets/products/mariachi-61.jpg"
 },
 {
  "row": 62,
  "name": "Decoración con globos sencilla",
  "cat": "decoracion",
  "desc": "100 a 150 globos",
  "price": 13000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎈",
  "img": "assets/products/decoracion-con-globos-sencilla-62.jpg"
 },
 {
  "row": 63,
  "name": "Decoración para cumpleaños (set principal y alrededores)",
  "cat": "decoracion",
  "desc": "Set principal y alrededores · 200 a 250 globos · Detalles personalizados",
  "price": 25000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎈",
  "img": "assets/products/decoracion-para-cumpleanos-set-principal-y-alrededores-63.jpg"
 },
 {
  "row": 64,
  "name": "Decoración interior (set principal)",
  "cat": "decoracion",
  "desc": "Set principal · 150 a 200 globos",
  "price": 17000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎈",
  "img": "assets/products/decoracion-interior-set-principal-64.jpg"
 },
 {
  "row": 65,
  "name": "Decoración de espacios grandes para 15 años",
  "cat": "decoracion",
  "desc": "Set principal y sus alrededores. · Globos 400 a 450. · Flores. · Cortinas. · Manteles. · Moño para sillas.",
  "price": 50000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎈",
  "img": "assets/products/decoracion-de-espacios-grandes-para-15-anos-65.jpg"
 },
 {
  "row": 66,
  "name": "Carne de cerdo asada Piernas",
  "cat": "combos_alimentos",
  "desc": "Piernas, lomos asados de 8 libra en adelante.",
  "price": 1800,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🍗",
  "img": "assets/products/carne-de-cerdo-asada-piernas-66.jpg"
 },
 {
  "row": 67,
  "name": "Jamón de pollo",
  "cat": "combos_alimentos",
  "desc": "Pollo hecho jamón · calidad extrema · Compra mínima 5 libra",
  "price": 1700,
  "unit": "unidad",
  "unit_label": "libra",
  "icon": "🍗",
  "img": "assets/products/jamon-de-pollo-67.jpg"
 },
 {
  "row": 68,
  "name": "Paquetes de pollo",
  "cat": "combos_alimentos",
  "desc": "Muslo o Contramuslo · Según disponibilidad.",
  "price": 8500,
  "unit": "unidad",
  "unit_label": "paquete",
  "icon": "🍗",
  "img": "assets/products/paquetes-de-pollo-68.jpg"
 },
 {
  "row": 69,
  "name": "Paquete de arroz",
  "cat": "combos_alimentos",
  "desc": "1kg · Precio:",
  "price": 1300,
  "unit": "unidad",
  "unit_label": "paquete",
  "icon": "🍗",
  "img": "assets/products/paquete-de-arroz-69.jpg"
 },
 {
  "row": 70,
  "name": "Galletas de soda",
  "cat": "combos_alimentos",
  "desc": "7 paquetes",
  "price": 2200,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🍗",
  "img": "assets/products/galletas-de-soda-70.jpg"
 },
 {
  "row": 71,
  "name": "Fili de huevo",
  "cat": "combos_alimentos",
  "desc": "30 unidades",
  "price": 6000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🍗",
  "img": "assets/products/fili-de-huevo-71.jpg"
 },
 {
  "row": 72,
  "name": "Yogurt natural",
  "cat": "combos_alimentos",
  "desc": "Sin azúcar añadido · 2 litro.",
  "price": 1000,
  "unit": "unidad",
  "unit_label": "2 litros",
  "icon": "🍗",
  "img": "assets/products/yogurt-natural-72.jpg"
 },
 {
  "row": 73,
  "name": "Mayonesa casera",
  "cat": "combos_alimentos",
  "desc": "350g.",
  "price": 1500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🍗",
  "img": "assets/products/mayonesa-casera-73.jpg"
 },
 {
  "row": 74,
  "name": "Pan suave",
  "cat": "combos_alimentos",
  "desc": "Formato en barra",
  "price": 200,
  "unit": "unidad",
  "unit_label": "unidad",
  "icon": "🍗",
  "img": "assets/products/pan-suave-74.jpg"
 },
 {
  "row": 75,
  "name": "Azúcar blanca",
  "cat": "combos_alimentos",
  "desc": "Venta mínima 5 libra",
  "price": 600,
  "unit": "unidad",
  "unit_label": "1 libra",
  "icon": "🍗",
  "img": "assets/products/azucar-blanca-75.jpg"
 },
 {
  "row": 76,
  "name": "Combo para cumpleaños (20 personas)",
  "cat": "combos_cumple",
  "desc": "20 personas · Incluye · 20 Croquetas fritas · 20 churros · 20 empanadillas · 20 mini donas · 20panecillos con pasta · 20 rosquitas de azúcar",
  "price": 7750,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎉",
  "img": "assets/products/combo-para-cumpleanos-20-personas-76.jpg"
 },
 {
  "row": 77,
  "name": "Combo para cumpleaños (30 personas)",
  "cat": "combos_cumple",
  "desc": "30 personas · Incluye · 30 Croquetas fritas · 30 churros · 30 empanadillas · 30 mini donas · 30panecillos con pasta · 30 rosquitas de azúcar",
  "price": 11500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎉",
  "img": "assets/products/combo-para-cumpleanos-30-personas-77.jpg"
 },
 {
  "row": 78,
  "name": "Combo para cumpleaños (75 personas)",
  "cat": "combos_cumple",
  "desc": "75personas · Incluye · 75Croquetas fritas · 75churros · 75 empanadillas · 75mini donas · 75panecillos con pasta · 75 rosquitas de azúcar · :",
  "price": 27500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎉",
  "img": "assets/products/combo-para-cumpleanos-75-personas-78.jpg"
 },
 {
  "row": 79,
  "name": "Combo de confituras",
  "cat": "combos_cumple",
  "desc": "Combo surtido de confituras · Varias opciones · Según disponibilidad.",
  "price": 8000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🎉",
  "img": "assets/products/combo-de-confituras-79.jpg"
 },
 {
  "row": 80,
  "name": "Pomos de refresco",
  "cat": "combos_alimentos",
  "desc": "1.5lit · Sabores según disponibilidad",
  "price": 1800,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🍗",
  "img": "assets/products/pomos-de-refresco-80.jpg"
 },
 {
  "row": 81,
  "name": "Malta guajira",
  "cat": "combos_alimentos",
  "desc": "Compra mínima 5 unidades",
  "price": 650,
  "unit": "unidad",
  "unit_label": "unidad",
  "icon": "🍗",
  "img": "assets/products/malta-guajira-81.jpg"
 },
 {
  "row": 82,
  "name": "Refresco gaseado",
  "cat": "combos_alimentos",
  "desc": "24 unidades · Sabores según disponibilidad",
  "price": 11500,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🍗",
  "img": "assets/products/refresco-gaseado-82.jpg"
 },
 {
  "row": 83,
  "name": "Cerveza Hollandia",
  "cat": "combos_alimentos",
  "desc": "24 unidades",
  "price": 12000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🍗",
  "img": "assets/products/cerveza-hollandia-83.jpg"
 },
 {
  "row": 84,
  "name": "Botella de whisky",
  "cat": "combos_alimentos",
  "desc": "Puede escoger en el momento entre las ofertas según disponibilidad.",
  "price": 4000,
  "unit": "pedido",
  "unit_label": null,
  "icon": "🍗",
  "img": "assets/products/botella-de-whisky-84.jpg"
 }
];
